### ISSUE TITLE
error when using snpmatch, throw error if bcftools doesnt exist in the path

### ISSUE THREAD

**Issue by vinay104** [Gregor-Mendel-Institute/SNPmatch#10]
Hello Mr. Rahul,

I am Vinay, a master student from University of Hohenheim, i decided to use snpmatch as a propability test check my master thesis samples of maize with related original varieties from CIMMYT. I ran the command to create a database file from original samples of cimmyt but i encountered with following error. Can you please check and help me out of this issue.

Error is as folows:
2018-08-08 12:23:14,565 - root - ERROR - 
Traceback (most recent call last):
  File "/afs/uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py", line 163, in main
    args['func'](args)
  File "/afs/uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py", line 139, in makedb_vcf_to_hdf5
    makedb.makedb_from_vcf(args)
  File "/afs/uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/makedb.py", line 85, in makedb_from_vcf
    makeHDF5s(args['db_id'] + '.csv', args['db_id'])
  File "/afs/uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/makedb.py", line 73, in makeHDF5s
    GenotypeData = genotype.load_csv_genotype_data(csvFile)
  File "/afs/uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/pygwas/core/genotype.py", line 47, in load_csv_genotype_data
    data = data_parsers.parse_genotype_csv_file(csv_files,format)
  File "/afs/uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/pygwas/core/data_parsers.py", line 80, in parse_genotype_csv_file
    first_line = reader.next()
StopIteration

Thanks,
Vinay Kumar Reddy NANNURU

**Comment by rbpisupati** [comment]
Hi Vinay, 

Can you also post top 10 lines of your input file? I assume you are running the above command to generate database hdf5 files, so are you providing VCF file or as CSV?


Rahul

**Comment by vinay104** [comment]
Dear Rahul,

I used vcf file as input as mentioned in the paper from you. And ten lines
of input vcf file:

##fileformat=VCFv4.2
##filedate=20180705
##source="beagle.21Jan17.6cc.jar (version 4.1)"
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated ALT Allele
Frequencies">
##INFO=<ID=AR2,Number=1,Type=Float,Description="Allelic R-Squared:
estimated squared correlation between most probable REF dose and true REF
dose">
##INFO=<ID=DR2,Number=1,Type=Float,Description="Dosage R-Squared: estimated
squared correlation between estimated REF dose [P(RA) + 2*P(RR)] and true
REF dose">
##INFO=<ID=IMP,Number=0,Type=Flag,Description="Imputed marker">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DS,Number=A,Type=Float,Description="estimated ALT dose [P(RA)
+ P(AA)]">
##FORMAT=<ID=GP,Number=G,Type=Float,Description="Estimated Genotype
Probability">
#CHROM  POS     ID    REF     ALT     QUAL    FILTER  INFO    FORMAT
C277b   C277a   C715c   C715b   C528a   C528c
1    55434   S1_55434        C    T    .    PASS    .    GT      0|0
1|0     0|0     0|1     0|1     0|1
1    695527  S1_695527    G    A    .    PASS    .    GT      0|1
0|0     1|0     0|1     0|1     0|0
1    695555  S1_695555    A    G    .    PASS    .    GT      0|1
0|0     1|0     0|1     0|1     0|0

Thanks,
Vinay Kumar Reddy NANNURU

**Comment by rbpisupati** [comment]
Ok! I am trying to replicate the error here. Can you post the entire command you used? Also can you run it using -v option to get verbosed output and post it here.


Rahul

**Comment by vinay104** [comment]
Hello Mr. Rahul,

This is entire command i used
(.SNPmatch) vinay410@server230:.SNPmatch > snpmatch makedb -v -i
//storage2/active/nvinay/mthesis/vcf/onlyoriginal.vcf.recode.vcf -o db

with -v i got this
 from . import _stats
2018-08-08 13:34:22,614 - snpmatch.core.makedb - INFO - converting VCF to
CSV
2018-08-08 13:34:22,617 - snpmatch.core.makedb - INFO - running bcftools!
[main] Unrecognized command.
2018-08-08 13:34:22,628 - snpmatch.core.makedb - INFO - done!
2018-08-08 13:34:22,629 - snpmatch.core.makedb - INFO - converting CSV to
hdf5!
2018-08-08 13:34:22,630 - pygwas.core.genotype - INFO - Loading Genotype
file
2018-08-08 13:34:22,630 - pygwas.core.data_parsers - INFO - Parsing
Genotype file (CSV) db.csv in format binary
2018-08-08 13:34:22,635 - pygwas.core.data_parsers - INFO - 6 accessions
found ['C277b', 'C277a', 'C715c', 'C715b', 'C528a', 'C528c']
2018-08-08 13:34:22,635 - root - ERROR -
Traceback (most recent call last):
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py",
line 163, in main
    args['func'](args)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py",
line 139, in makedb_vcf_to_hdf5
    makedb.makedb_from_vcf(args)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/makedb.py",
line 85, in makedb_from_vcf
    makeHDF5s(args['db_id'] + '.csv', args['db_id'])
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/makedb.py",
line 73, in makeHDF5s
    GenotypeData = genotype.load_csv_genotype_data(csvFile)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/pygwas/core/genotype.py",
line 47, in load_csv_genotype_data
    data = data_parsers.parse_genotype_csv_file(csv_files,format)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/pygwas/core/data_parsers.py",
line 80, in parse_genotype_csv_file
    first_line = reader.next()
StopIteration

Thanks,
Vinay Kumar Reddy Nannuru

**Comment by rbpisupati** [comment]
Seems like you dont have bcftools tools installed in the default bin folder. If you installed it in some other location, provide the path using -b option in the command. 

Let me know if it works by installing bcftools,


Rahul

**Comment by vinay104** [comment]
Hello Mr Rahul,

I have this error again saying invalid option "snpmatch: error:
unrecognized arguments: -b /usr/bin/bcftools". Full log below

(.SNPmatch) vinay410@server230:~ > snpmatch makedb -b /usr/bin/bcftools -i
//storage2/active/nvinay/mthesis/vcf/onlyoriginal.vcf.recode.vcf -o db
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/special/__init__.py:640:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._ufuncs import *
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/linalg/basic.py:17:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/linalg/__init__.py:207:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._decomp_update import *
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from . import _bspl
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/sparse/lil.py:19:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from . import _csparsetools
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:165:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:170:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee,
maximum_bipartite_matching, \
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/spatial/__init__.py:95:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from .ckdtree import *
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/spatial/__init__.py:96:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from .qhull import *
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from . import _voronoi
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/spatial/distance.py:122:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from . import _hausdorff
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/optimize/_trlib/__init__.py:1:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:10:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:18:
RuntimeWarning: numpy.dtype size changed, may indicate binary
incompatibility. Expected 96, got 88
  from . import _stats
usage: snpmatch [-h] [-V]
                {inbred,cross,genotype_cross,parser,pairsnp,makedb} ...
snpmatch: error: unrecognized arguments: -b /usr/bin/bcftools

Thanks,
Vinay Kumar Reddy NANNURU

**Comment by rbpisupati** [comment]
Hi, 

Sorry, the option you need to use is -p instead of -b.

**Comment by vinay104** [comment]
Hello Mr Rahul,

Now also i see an error, here is the log

2018-08-08 15:17:12,369 - snpmatch.core.makedb - INFO - converting VCF to
CSV
2018-08-08 15:17:12,372 - snpmatch.core.makedb - INFO - running bcftools!
/bin/sh: /usr/bin/bcftools1.4/bcftools: Not a directory
2018-08-08 15:17:12,383 - snpmatch.core.makedb - INFO - done!
2018-08-08 15:17:12,385 - snpmatch.core.makedb - INFO - converting CSV to
hdf5!
2018-08-08 15:17:12,385 - pygwas.core.genotype - INFO - Loading Genotype
file
2018-08-08 15:17:12,385 - pygwas.core.data_parsers - INFO - Parsing
Genotype file (CSV) db.csv in format binary
2018-08-08 15:17:12,390 - pygwas.core.data_parsers - INFO - 6 accessions
found ['C277b', 'C277a', 'C715c', 'C715b', 'C528a', 'C528c']
2018-08-08 15:17:12,390 - root - ERROR -
Traceback (most recent call last):
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py",
line 163, in main
    args['func'](args)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py",
line 139, in makedb_vcf_to_hdf5
    makedb.makedb_from_vcf(args)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/makedb.py",
line 85, in makedb_from_vcf
    makeHDF5s(args['db_id'] + '.csv', args['db_id'])
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/makedb.py",
line 73, in makeHDF5s
    GenotypeData = genotype.load_csv_genotype_data(csvFile)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/pygwas/core/genotype.py",
line 47, in load_csv_genotype_data
    data = data_parsers.parse_genotype_csv_file(csv_files,format)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/pygwas/core/data_parsers.py",
line 80, in parse_genotype_csv_file
    first_line = reader.next()
StopIteration

Thanks,
Vinay Kumar Reddy NANNURU

**Comment by rbpisupati** [comment]
For some reason bcftools installation is not taken by program. Does bcftools binary file exists in here "/usr/bin/bcftools1.4/bcftools" ? If not check the path once again.

**Comment by rbpisupati** [comment]
If you installed bcftools systemwide, then you dont need to put any -p option. Just try running without any -p option.

**Comment by vinay104** [comment]
Hello Mr Rahul,

Path is correct and i used this many times, can you check if it works with
you. Can i send you my file.

Thanks,
Vinay Kumar Reddy NANNURU

**Comment by rbpisupati** [comment]
Yes, send me the file. But did you try running command without -p, since that now you installed bcftools? /usr/bin does by default exists in PATH variable.

**Comment by vinay104** [comment]
Hello Mr Rahul,

I did already send the file with last email. That usr/bin/bcftoolos is
global available in my institute server.

Thanks,
Vinay

**Comment by rbpisupati** [comment]
Can you update SNPmatch using pip (from github repo) and check if it works?

**Comment by vinay104** [comment]
Hello Mr Rahul,

I did as you said and now it says this error
Error: please provide bcftools installation path. '/usr/bin/bcftools' is
not found!
But bcftools is at following path provided

thanks,
vinay

**Comment by rbpisupati** [comment]
Yes, the bcftools installation is not proper for the system. Try installing bcftools locally (not in /usr/bin) in your folder and give that as the path.

**Comment by vinay104** [comment]
Hello Mr Rahul,

Yes, now it works and  agian another error while using this command

snpmatch inbred -d db.hdf5 -e db.acc.hdf5 -i
//storage2/active/nvinay/mthesis/vcf/nooriginal.vcf.recode.vcf -v -o outfile

| 2018-08-09 16:17:37,256 - snpmatch.core.parsers - INFO - running snpmatch
parser!
2018-08-09 16:17:37,256 - snpmatch.core.parsers - INFO - reading the VCF
file
2018-08-09 16:17:37,423 - root - ERROR - 'calldata/DP'
Traceback (most recent call last):
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py",
line 191, in main
    args['func'](args)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/__init__.py",
line 116, in snpmatch_inbred
    snpmatch.potatoGenotyper(args)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/snpmatch.py",
line 153, in potatoGenotyper
    (snpCHR, snpPOS, snpGT, snpWEI, DPmean) = parsers.parseInput(inFile =
args['inFile'], logDebug = args['logDebug'])
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/parsers.py",
line 104, in parseInput
    (DPmean, snpCHR, snpPOS, snpGT, snpWEI) = readVcf(inFile, logDebug)
  File "/afs/
uni-hohenheim.de/hhome/v/vinay410/.SNPmatch/lib/python2.7/site-packages/snpmatch/core/parsers.py",
line 84, in readVcf
    DPmean = np.mean(vcf['calldata/DP'][snpsREQ,0])
KeyError: 'calldata/DP' |

And whwn i use this


snpmatch inbred -d db.hdf5 -e db.acc.hdf5 -i
//storage2/active/nvinay/mthesis/vcf/nooriginal.vcf.recode.vcf -v / -o
outfile

usage: snpmatch [-h] [-V]
                {inbred,cross,genotype_cross,parser,pairsnp,makedb,simulate}
                ...
snpmatch: error: unrecognized arguments:  -o outfile


Thanks,
Vinay Kumar Reddy Nannuru

**Comment by rbpisupati** [comment]
Can you send me the input file?

**Comment by vinay104** [comment]
Dear Rahul,

So, here is the input file. Thank you

**Comment by rbpisupati** [comment]
Ok! the above update should fix the problem. Can you update it one more time and check?

**Comment by vinay104** [comment]
Dear Rahul,

I will do it tomorrow and let you know, as I got urgent work to do, i am
out from my work place just now.

Regards,
Vinay Kumar Reddy NANNURU

**Comment by vinay104** [comment]
Hey,

I just signed the petition ".@PrakashJavdekar @SuPriyoBabul : Declaration
of a National Climate Emergency and Tackling of Climate Change" and wanted
to see if you could help by adding your name.

Our goal is to reach 300,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/Tz8y9jtqDB

Thanks!
Vinay Kumar Reddy
