### ISSUE TITLE
Link to database is incorrect

### ISSUE THREAD

**Issue by JoseMMuino** [Gregor-Mendel-Institute/SNPmatch#19]
Dear,
Thanks for your tool.

Sadly the link to the SNP database for the 1001genome project doesn't work. In the main page it is said that we can download from https://gmioncloud-my.sharepoint.com/personal/uemit_seren_gmi_oeaw_ac_at/_layouts/15/guestaccess.aspx?folderid=0ca806e676c154094992a9e89e5341d43&authkey=AXJPl6GkD8vNPDZJwheb6uk

From where I can get the database to tun SNPmatch?

Best,
Jose

**Comment by rbpisupati** [comment]
Hello Jose!

Thank you for pointing it out! We have uploaded the data in figshare are in the paper, and here are the links. Shall update these links in the Readme

https://figshare.com/collections/_/3722743



Cheers, 
R
