### ISSUE TITLE
Trouble creating SNP database files

### ISSUE THREAD

**Issue by blthree** [Gregor-Mendel-Institute/SNPmatch#6]
Hi,

I am confused about how to create a the hdf5 SNP database files for SNPmatch. I modified 01.convertVCF_SNPmat_csv.sh in /scripts to work for my setup, and it works fine to create the .csv file, but it fails once it calls 02.convertSNPmat_csv_HDF5.py with the following error in data_parsers.py line 108 from pygwas.core.

`ValueError: invalid literal for long() with base 10: '0|0:36:4'`

I forgot to grab the whole traceback, but I will add it when I can. Do you have any instructions for generating the database file or can you point me to some good vcf files I can test to see if I am making a mistake somewhere? Thanks!

VCF file:
I am using "1001genomes_snp-short-indel_only_ACGTN.vcf.gz" from http://1001genomes.org/data/GMI-MPI/releases/v3.1/ .

System Info: 
ubuntu 16.04
python 2.7.13

**Comment by rbpisupati** [comment]
Hi, 

The csv file that has been converted should have binary SNP data. From the error you are having '0|0:36:4' instead of just 0 for homozygous SNP. The awk script to convert to binary is probably not functioning. Try this "" substr($i,1,3) ~ /1.1/ "" instead for all the substr.

Also make sure you remove indels, just use SNP data.


Rahul

**Comment by blthree** [comment]
Thanks Rahul,

It was definitely caused by some changes I made to the awk script as well as not filtering the vcf for biallelic only. I had multiple versions of both the shell script and the python script with different changes. I had to change make changes (removing load module etc to get the script to run and I messed up some quoting in the script.

I started with a correct version of the script and converting to binary csv worked fine. Right now it is converting to hdf5, but the last logging message was "finished with chr4" which was about to an hour ago, compared to a only about 5 minutes total time for chr1 thru 4. I'm keeping my fingers crossed it'll finish soon. 

Thanks again for your help

**Comment by timeu** [comment]
@blthree Do you want to run SNPMatch with your own genotype data ? If not we can also provide the HDF5 files, so you don't need to convert them.

**Comment by blthree** [comment]
@timeu If you could provide the HDF5 files that would be great. For the present, I'm just planning on running against 1001 genomes and regmap. At some point, I'd like to get some of my own data set up, but that's really just a side project of mine.

**Comment by timeu** [comment]
@blthree : Ok I will upload the matrices for Regmap (~158 Mb) and the 1001 genomes (~5GB) tomorrow and put a link here and update the README.md.

**Comment by timeu** [comment]
@blthree Updated the README.md let me know if it works for you

**Comment by blthree** [comment]
Thanks @timeu and @rbpisupati . Downloaded the hdf5 files and SNPmatch is working smoothly!
